# Dex OIDC configuration for development environment
#
# LDAP Connector Configuration:
# - Uses OpenLDAP as the authentication backend
# - LDAP endpoint: openldap-0.openldap-headless.ldap.svc.cluster.local:389
# - Domain: dc=ldap,dc=localhost
# - Users: ou=people,dc=ldap,dc=localhost
# - Groups: ou=groups,dc=ldap,dc=localhost

image:
  tag: v2.38.0

# Use HTTP for development simplicity (no certificates needed)
https:
  enabled: false

# Disable gRPC to avoid additional port conflicts
grpc:
  enabled: false

config:
  issuer: http://dex.localhost

  storage:
    type: kubernetes
    config:
      inCluster: true

  connectors:
    - type: ldap
      name: OpenLDAP
      id: ldap
      config:
        # Use headless service to reach pod directly on its actual port
        host: openldap-0.openldap-headless.ldap.svc.cluster.local:389

        # No TLS for development setup
        insecureNoSSL: true

        # Admin credentials for LDAP binding
        bindDN: cn=admin,dc=ldap,dc=localhost
        bindPW: password

        usernamePrompt: Email Address

        userSearch:
          baseDN: ou=people,dc=ldap,dc=localhost
          filter: "(objectClass=person)"
          username: mail
          idAttr: DN
          emailAttr: mail
          nameAttr: cn

        groupSearch:
          baseDN: ou=groups,dc=ldap,dc=localhost
          filter: "(objectClass=groupOfNames)"
          userAttr: DN
          groupAttr: member
          nameAttr: cn

  oauth2:
    skipApprovalScreen: true

  staticClients:
    - id: argocd
      redirectURIs:
        - "http://argocd.localhost/auth/callback"
      name: "ArgoCD Development"
      secret: argocd-secret

    - id: grafana
      redirectURIs:
        - "http://grafana.localhost/login/generic_oauth"
      name: "Grafana Development"
      secret: grafana-secret

    - id: forgejo
      redirectURIs:
        - "http://forgejo.localhost/user/oauth2/dex/callback"
      name: "Forgejo Development"
      secret: forgejo-secret

service:
  type: NodePort
  ports:
    http:
      nodePort: 32000
      port: 5556
      targetPort: 5556

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: dex.localhost
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 20Mi
