kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-local
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
    extraPortMappings:
      # HTTP ingress for accessing dex.localhost, argocd.localhost, etc.
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # Dex OIDC NodePort for direct access (http://localhost:32000)
      - containerPort: 32000
        hostPort: 32000
        protocol: TCP